list=('Computer','Input Device','Output Device','Memory Device','Cache Memory','Registers','Random Access Memory (RAM)','Read Only Memory (ROM)','Hard Disk','Pen Drive','Compact Disc (CD)','Floppy Disk','Bit','Byte','Kilobyte (kB)','Megabyte (MB)','Gigabyte (GB)','Terabyte (TB)', 'Operating System (OS)','Programming Language','Application Programs','ASCII value','utf format','Compiler','Assembler','POST operation','second','millisecond','microsecond','nanosecond','Read Operation','Write Operation','Append Operation','Number System','Binary Number System','Octal Number System','Decimal Number System','HexaDecimal Number System','IP Address','MAC Address')



class Content():
    
    computer='A [b]Computer[/b] is an electronic device that takes raw data (unprocessed) as an input from the user and processes it under the control of a set of instructions (called program), produces a result (output), and saves it for future use.Growth in the computer industry is determined by the development in technology. \n\nBased on various stages of development, computers can be categroised into different generations. Charles Babbage is considered to be the father of computer, for his invention and the concept of Analytical Engine in 1837. \n\nThe Analytical Engine contained an Arithmetic Logic Unit (ALU),basic flow control, and integrated memory;which led to the development of first generalpurpose computer concept.'
    
    
    
    
    input_device='An [b]Input Device[/b] is any hardware device that sends data to a computer, allowing you to interact with and control it. The most commonly used or primary input devices on a computer are the keyboard and mouse. However, there are other devices that input data into a computer.\n\nFew of the input devices are,\n     • Keyboard\n     • Mouse\n     • Scanner\n     • Fingerprint Scanner\n     • TrackBall\n     • Retinal Scanner\n     • Touch Screen\n\nMouse are the most commonly used input devices today. A mouse is any human interface device that allows a user to input spatial data to a computer. In the case of mouse and touchpads, this is usually achieved by detecting movement across a physical surface.'
    
    
    output_device='An [b]Output Device[/b] is a piece of computer hardware that receives data from a computer and then translates that data into another form. That form may be audio, visual, textual, or hard copy such as a printed document. The key distinction between an input device and an output device is that an input device sends data to the computer, whereas an output device receives data from the computer.\n\nA display device is the most common form of output device. It presents output visually on computer screen. The output appears temporarily on the screen and can easily altered or erased, it is sometimes referred to as soft copy also. The display device for a desktop PC is called monitor.\n\nFew of the Output Devices are,\n     • Monitor\n     • Printer\n     • Speaker\n     • Projector'
    
    
    
    memory_device='The [b]Memory Unit[/b] is of two types which are primary memory and secondary memory. The primary memory is used to temporarily store the programs and data when the instructions are ready to execute. The secondary memory is used to store the data permanently.\n\nThe Primary Memory is volatile, that is, the content is lost when the power supply is switched off. The Random Access Memory (RAM) is an example of a main memory. \n\nThe Secondary memory is non volatile, that is, the content is available even after the power supply is switched off. Hard disk, CD-ROM and DVD ROM are examples of secondary memory.\n\nFew of the memory devices are,\n     • Pen drive\n     • Compact Disc\n     • Floppy Disk'
    
    cache_memory='The [b]Cache Memory[/b] is a very high speed and expensive memory, which is used to speed up the memory retrieval process. Due to its higher cost, the CPU comes with a smaller size of cache memory compared with the size of the main memory. \n\nWithout cache memory, every time the CPU requests the data, it has to be fetched from the main memory which will consume more time. The idea of introducing a cache is that, this extremely fast memory would store data that is frequently accessed and if possible, the data that is closer to it. \n\nThis helps to achieve the fast response time, Where response Time, (Access Time) refers to how quickly the memory can respond to a read / write request.'
    
    registers='[b]Register[/b] are used to quickly accept, store, and transfer data and instructions that are being used immediately by the CPU, there are various types of Registers those are used for various purpose. \n\nAmong of the some Mostly used Registers named as AC or Accumulator, Data Register or DR, the AR or Address Register, program counter (PC), Memory Data Register (MDR), Index register, Memory Buffer Register.These Registers are used for performing the various Operations. While we are working on the System then these Registers are used by the CPU for Performing the Operations. \n\nWhen We Gives Some Input to the System then the Input will be Stored into the Registers and When the System will gives us the Results after Processing then the Result will also be from the Registers. So that they are used by the CPU for Processing the Data which is given by the User.'
    
    ram='The main memory is otherwise called as [b]Random Access Memory[/b]. This is available in computers in the form of Integrated Circuits (ICs). It is the place in a computer where the Operating System, Application Programs and the data in current use are kept temporarily so that they can be accessed by the computer’s processor. \n\nThe smallest unit of information that can be stored in the memory is called as a bit. The memory can be accessed by a collection of 8 bits which is called as a byte.\n\n[b]RAM[/b] is a volatile memory, which means that the information stored in it is not permanent. As soon as the power is turned off, whatever data that resides in RAM is lost. It allows both read and write operations.\n\nThere are two basic types of RAM,\n     • Dynamic RAM (DRAM)\n     • Static RAM (SRAM)'
     
    rom='[b]Read Only Memory[/b] refers to special memory in a computer with pre-recorded data at manufacturing time which cannot be modified. The stored programs that start the computer and perform diagnostics are available in ROMs. \n\nROM stores critical programs such as the program that boots the computer. Once the data has been written onto a ROM chip, it cannot be modified or removed and can only be read. ROM retains its contents even when the computer is turned off. So, ROM is called as a non-volatile memory.\n\nTypes of ROM,\n     • Programmable Read Only Memory\n     • Erasable Programmable Read Only Memory\n     • Electrically Erasable Programmable Read Only Memory'
    
    
    hard_disk='[b]Hard Disk[/b], also called hard disk drive or hard drive, magnetic storage medium for a computer. Hard disks are flat circular plates made of aluminum or glass and coated with a magnetic material. \n\nHard disks for personal computers can store terabytes (trillions of bytes) of information. Data are stored on their surfaces in concentric tracks. A small electromagnet, called a magnetic head, writes a binary digit (1 or 0) by magnetizing tiny spots on the spinning disk in different directions and reads digits by detecting the magnetization direction of the spots. \n\nA computer’s hard drive is a device consisting of several hard disks, read/write heads, a drive motor to spin the disks, and a small amount of circuitry, all sealed in a metal case to protect the disks from dust. In addition to referring to the disks themselves, the term hard disk is also used to refer to the whole of a computer’s internal data storage.'
    
    pen_drive="A [b]Pen Drive[/b] is a portable Universal Serial Bus (USB) flash memory device for storing and transferring audio, video, and data files from a computer. As long as the desktop or laptop has a USB port, and the pen drive is compatible with the operating system, it should be easy to move the data from the hard drive to the device and to another computer in a matter of minutes. \n\nThe drive gets its name from the fact that many have a retractable port connector like a ballpoint pen, and they are small enough to fit into a pocket. Other names include flash drive, jump drive, and thumb drive.\n\nThe actual transfer speed depends upon several factors, such as the computer's speed at reading and writing to the device. Generally, a pen drive's advertised speed is the reading speed because it is faster than the speed at which data can be written to it. Manufacturers usually list the speed in megabytes per second (MB/s). The age of the drive and how it's being used such as for writing and erasing small files also affects the transfer speed."
    
    cd='A [b]Compact Disc[/b] is a portable storage medium that can be used to record, store and play back audio, video and other data in digital form. \n\nA standard compact disc measures 4.7 inches, or 120 millimeters (mm), across, is 1.2 mm thick, weighs between 15 grams and 20 grams, and has a capacity of 80 minutes of audio, or 650 megabytes (MB) to 700 MB of data. A CD works by focusing a 780 nanometer wavelength semiconductor laser onto a single track of the disc. \n\nAs the disc rotates, the laser beam measures differences in the way light is reflected off the polycarbonate layer on the bottom of the disc, converting it to sound.CDs are fragile and prone to scratches; they can be repaired, but disc readability may be affected.'
    
    floppy_disk='A [b]Floppy Disk[/b] is a type of storage media that reads data storage information, also known as a floppy diskette, floppy, or floppy disk that is used to store electronic data, like a computer file. It was extremely expensive as it was one of the first types of hardware storage created in 1967 by IBM, which could read/write a portable device.\n\nFloppy disks do not have more storage capacity that leads them to be unappropriated for storing high-resolution photos, music, videos, etc. Although floppy disks have shortcomings, they also have some notable advantages.\n\nTypes of floppy disk,\n     • 8 - inch Drive\n     • 5 ¼ - inch Drive\n     • 3 ½ - inch Drive\n     • Zip Drive'
    
    bit='A [b]Bit[/b] (short for binary digit) is the smallest unit of data in a computer. A bit has a single binary value, either 0 or 1. Although computers usually provide instructions that can test and manipulate bits, they generally are designed to store data and execute instructions in bit multiples called bytes. In most computer systems, there are eight bits in a byte. The value of a bit is usually stored as either above or below a designated level of electrical charge in a single capacitor within a memory device.\n\nHalf a byte (four bits) is called a nibble. In some systems, the term octet is used for an eight-bit unit instead of byte. In many systems, four eight-bit bytes or octets form a 32-bit word. In such systems, instruction lengths are sometimes expressed as full-word (32 bits in length) or half-word (16 bits in length).\n\nThe speed of a computer depends on the number of bits it can process at once. For example, a 64- bit computer can process 64-bit numbers in one operation, while a 32-bit computer break 64-bit numbers down into smaller pieces, making it slower.'
    
    byte='A collection of 8 bits is called [b]Byte[/b]. A byte is considered as the basic unit of measuring the memory size in the computer.Bytes are used to represent characters in a text.\n\nWhile bytes are measured in bit multiples, computer storage is typically measured in byte multiples. In many computer architectures, a byte is the smallest addressable unit of memory. For example, an 820 megabyte (MB) hard drive holds a nominal 820 million bytes of data. Due to massive increases in storage capacity over time, there are now eight additional units of measurement following the byte. The eight different types of bytes currently used in computer architectures range from kilobytes (1,024 bytes) to yottabytes (1,024 zettabytes).Byte multiples can be measured using two systems: base-2 or base-10.'
    
    kb='A [b]kilobyte[/b] (KB) is a multiple unit used for binary data. Although "kilo" generally refers to 1,000, in computer science, one kilobyte often refers to 1,024 (2^10) bytes. It may also be used to refer to 1,000 bytes depending on the context. This measure is often used to describe memory capacity and disk storage.\n\nThe term kilobyte is generally used to describe small amounts of data stored on computers, as well as small files. Types of files with a smaller average file size that tend to be measured in kilobytes include short emails, images and short papers or Microsoft Word documents.\n\nThe measurement kilobyte, along with other metric values, is determined by the International Electrotechnical Commission (IEC), an organization responsible for International Standards and Conformity Assessment for computer and electronic technologies.'
    
    mb='[b]Megabyte[/b] (MB) is a data measurement unit applied to digital computer or media storage. One MB equals one million (10^6 or 1,000,000) bytes. The International System of Units (SI) defines the mega prefix as a 10 multiplier or one million (1,000,000) bits. The binary mega prefix is 1,048,576 bits or 1,024 Kb. The SI and binary differential is approximately 4.86 percent.\n\nMegabytes are often used to measure the size of large files. For example, a high resolution JPEG image file might range is size from one to five megabytes. Uncompressed RAW images from a digital camera may require 10 to 50 MB of disk space. A three minute song saved in a compressed format may be roughly three megabytes in size, and the uncompressed version may take up 30 MB of space. While CD capacity is measured in megabytes (typically 700 to 800 MB), the capacity of most other forms of media, such as flash drives and hard drives, is typically measured in gigabytes or terabytes.'
    
    gb='A [b]Gigabyte[/b] is 1,000,000,000 bytes. One gigabyte (abbreviated "GB") is equal to 1,000 megabytes and precedes the terabyte unit of measurement. While a gigabyte is technically 1,000,000,000 bytes, in some cases, gigabytes are used synonymously with gibibytes, which contain 1,073,741,824 bytes (1024 x 1,024 x 1,024 bytes).\n\nGigabytes, sometimes abbreviated "gigs," are often used to measure storage capacity. For example, a standard DVD can hold 4.7 gigabytes of data. An SSD might hold 256 GB, and a hard drive may have a storage capacity of 750 GB. Storage devices that hold 1,000 GB of data or more are typically measured in terabytes.\n\nRAM is also usually measured in gigabytes. For example, a desktop computer may come with 16 GB of system RAM and 2 GB of video RAM. A tablet may only require 1 GB of system RAM since portable apps typically do not require as much memory as desktop applications.'
    
    tb="""A [b]Terabyte[/b] is 10^12 or 1,000,000,000,000 bytes.One terabyte (abbreviated "TB") is equal to 1,000 gigabytes and precedes the petabyte unit of measurement. While a terabyte is exactly 1 trillion bytes, in some cases terabytes and tebibytes are used synonymously, though a tebibyte actually contains 1,099,511,627,776 bytes (1,024 gibibytes).\n\nTerabytes are most often used to measure the storage capacity of large storage devices. While hard drives were measured in gigabytes for many years, around 2007, consumer hard drives reached a capacity of one terabyte. Now, all hard drives that have a capacity of 1,000 GB or more are measured in terabytes. For example, a typical internal HDD may hold 2 TB of data. Some servers and high-end workstations that contain multiple hard drives may have a total storage capacity of over 10 TB."""
    
    os='An [b]Operating System[/b] (OS) is a system software which serves as an interface between a user and a computer. This controls input, output and other peripheral devices such as disk drives, printers and electronic gadgets. The functions of an Operating System include file management, memory management, process management and device management and many more.\n\nWithout an Operating System, a computer cannot eff ectively manage all the resources. When a computer is switched on, the operating system is loaded in to the memory automatically. \n\nSome of the popular Operating Systems used in personal computers and laptops are Windows, UNIX and Linux. The mobile devices mostly use Android and ioS as mobile OS.'
    
    programming_language='A [b]Programming Language[/b] is a notation for expressing algorithms so that a computer can execute the algorithm. An algorithm expressed in a programming language is called a program. \n\nProgramming language is formal. Programs must obey the grammar of the programming language exactly. Even punctuation symbols must be exact. They do not allow the informal style of natural languages such as English or Tamil. There is a translator which translates the program into instructions executable by the computer. If our program has grammatical errors, this translator will not be able to do the translation.\n\nFew of the programming languages are,\n     • C\n     • C++\n     • Python\n     • Java etc...'
    
    application_programs='[b]Applications Programs[/b] are programs written to solve specific problems, to produce specific reports, or to update specific files. A computer program that performs useful work on behalf of the user of the computer (for example a word processing or accounting program) as opposed to the SYSTEM SOFTWARE which manages the running of the computer itself, or to the DEVELOPMENT software which is used by programmers to create other programs. \n\nAn application program is typically self contained, storing data within files of a special (often proprietary) format that it can create, open for editing and save to disk: this is in distinction to a UTILITY program, which typically performs simple operations on files created by other programs.\n\nComputer programs intended to perform user’s tasks, as opposed to those used by the computer itself or by programmers writing further programs.'
    
    ascii="[b]American Standard Code for Information Interchange[/b] (ASCII) is the most popular encoding system recognized by United States. Most of the computers use this system.This encoding system can handle English characters only. This can handle 27 bit which means 128 characters. In this system, each character has individual number. \n\nThe new edition (version) ASCII -8, has 28 bits and can handle 256 characters are represented from 0 to 255 unique numbers.The ASCII code equivalent to the uppercase letter ‘A’ is 65. ASCII offers a universally accepted and understood character set for basic data communications. It enables developers to design interfaces that both humans and computers understand.\n\nProgrammers use the design of the ASCII character set to simplify certain tasks. For example, using ASCII character codes, changing a single bit easily converts text from uppercase to lowercase."
    
    utf='[b]Unicode Transformation Format[/b], UTF is a universal standard for mapping Unicode encodings. It defines the way writing from anywhere in the world, stored in any Unicode encoding format, should be represented on different computer systems. For example, it defines the way UTF-16 (16-bit Unicode characters) should be converted to UTF-7 (7-bit) or UTF-8 (8-bit) characters.\n\nText document that uses Unicode UTF-8 (8-bit Unicode Transformation Format) encoding; can be used for English and many other languages, including support for Asian characters; backwards compatible with ASCII.\n\n16-bit Unicode Transformation Format is a variable-length character encoding for Unicode, capable of encoding the entire Unicode repertoire. UTF-16 is used in major operating systems and environments, like Microsoft Windows, Java and .NET.'
    
    compiler="""A [b]Compiler[/b] is a special program that processes statements written in a particular programming language and turns them into machine language or "code" that a computer's processor uses. Typically, a programmer writes language statements in a language such as Pascal or C one line at a time using an editor. The file that is created contains what are called the source statements. The programmer then runs the appropriate language compiler, specifying the name of the file that contains the source statements.\n\nWhen executing (running), the compiler first parses (or analyzes) all of the language statements syntactically one after the other and then, in one or more successive stages or "passes", builds the output code, making sure that statements that refer to other statements are referred to correctly in the final code. Traditionally, the output of the compilation has been called object code or sometimes an object module.The object code is machine code that the processor can execute one instruction at a time."""
    
    assembler="An [b]Assembler[/b] is a type of computer program that interprets software programs written in assembly language into machine language, code and instructions that can be executed by a computer. An assembler enables software and application developers to access, operate and manage a computer's hardware architecture and components.\n\nAn assembler is sometimes referred to as the compiler of assembly language. It also provides the services of an interpreter. An assembler primarily serves as the bridge between symbolically coded instructions written in assembly language and the computer processor, memory and other computational components. \n\nAn assembler works by assembling and converting the source code of assembly language into object code or an object file that constitutes a stream of zeros and ones of machine code, which are directly executable by the processor."
    
    post='A [b]Power-On Self-Test[/b] (POST) is a set of routines performed by firmware or software immediately after a computer is powered on, to determine if the hardware is working as expected. The process would proceed further only if the required hardware is working correctly, else the BIOS(Basic Input Output Software) would issue an error message. POST sequence is executed irrespective of the Operating System and is handled by the system BIOS. \n\nOnce the tests are passed the POST would generally notify the OS with beeps while the number of beeps can vary from system to system. When POST is successfully finalized, bootstrapping is enabled. Bootstrapping starts the initialization of the OS.\n\nThe boot sequence is the process of starting a computer/system. The boot process is initiated when the power button is pressed, it sends power to the boot-loader in the cache memory.'
    
    second="The [b]second[/b] (abbreviation, s or sec) is the Standard International ( SI ) unit of time. One second is the time that elapses during 9,192,631,770 (9.192631770 x 10^9 ) cycles of the radiation produced by the transition between two levels of the cesium 133 atom.\n\nThere are other expressions for the second. It is the time required for an electromagnetic field to propagate 299,792,458 meters (2.99792458 x 10^8 m) through a vacuum. This figure is sometimes rounded to 3.00 x 10^8 m, or 300,000 kilometers (3.00 x 10^5 km). One second is equal to 1/86,400 of a mean solar day. This is easy to derive from the fact that there are 60 seconds in a minute, 60 minutes in an hour, and 24 hours in a mean solar day. This definition is, however, subject to limited accuracy because of irregularities in the earth's orbit around the sun."
    
    milli_second='A [b]millisecond[/b] (ms or msec) is a unit of time that represents 1/1000th of a second. It is one of the more useful chronological measurements related to cycle speeds, central processor unit (CPU) operations and microprocessor design, as well as some forms of data transfer. There are also measurements in between seconds and milliseconds: A centisecond (cs or csec) is 100 ms, and a decisecond (ds or dsec) is 10 ms.\n\nThe millisecond is one of several increasingly small units used to measure time. In these chronological ranges, it becomes more difficult to identify technological ability and make these extremely short time frames relevant to evaluation. A millisecond can be used to assess computing activity in many ways. For example, this range is useful in assessing the access time of a disk drive or the time required to make an object available.\n\nExperts estimate the average disk access time of an above-average personal computer to be in the range of 9-15 ms.'
    
    micro_second='A [b]microsecond[/b] is a unit of time equal to one millionth of a second. It is also equal to one 1000th of a millisecond, or 1000 nanoseconds.\n\nMany of these units of very fine time measurement are used in high-tech laboratories where scientists measure data transfer unaffected by many of the usual limitations.\n\nThe microsecond is part of a string of time measurements that extends into extremely short periods of time. Although some types of technology use time measurements in the realm of microseconds, other uses involve difficulties related to the time that it takes to perform data transfer activities. For instance, some of the current debate on using microseconds revolves around millisecond and microsecond tools in programming languages like JavaScript, or in web browser technologies.'
    
    nano_second='A [b]nanosecond[/b] (ns) is equal to one billionth of a second. It is also equal to 1000th of a microsecond, or 1000 picoseconds. Nanosecond is sometimes abbreviated nsec.\n\nThe nanosecond is a particular measure of time that has been applied to information technology in many different ways. As technology improves, the nanosecond has become a common benchmark measurement for different types of scientific and digital processes.\n\nAs computer technology evolved, the nanosecond scale became a common way to measure the time that it takes for computers to access memory. These time frames are also often used for laser beam technologies and different kinds of light or radio frequency transmissions.'
    
    read_operation='The [b]Read Operation[/b] fetches data from memory and transfers to MDR. A single control line performs two operations like Read / Write using 1 or 0. Also, the write operation transfers data from the MDR to memory.\n\nThe word in the RAM has the same size (no. of bits) as the Memory Data Register (MDR). If the processor is an 8-bit processor like Intel 8085, its MDR and the word in the RAM both have 8 bits. If the size of the MDR is eight bits, which can be connected with a word of eight bits where the data can be stored or retrieved, the data bus has eight wires in parallel to transfer the data in any one direction which depends on whether the control is read or write.'
    
    write_operation='A [b]Write Operation[/b] is the transfer of a piece of data to some destination. The destination might be RAM - when a program, for example, sets the value of a variable. It might be a peripheral device, for example a hard disk, a flash drive, or a USB port. The destination might be a control element of a piece of hardware, for example control registers in a GPU. If the destination is the CPU itself, we would normally call it a read.\n\nMemory write operation transfers the address of the desired word to the address lines, transfers the data bits to be stored in memory to the data input lines. Then it activates the write control line. '
    
    append_operation='Adding more strings at the end of an existing string is known as [b]Append[/b].\n\nThe append operation:\n     • locks the master file\n     • appends all the records from the transaction file\n     • updates any indexes\n\nThis speeds up merges of large files. If any one else has the master table open, or if you open another form using the master table, the append will update the indexes after each record append.\n\nIn python append() fuction is used to add elements to the list. += is used to append a string to another string.'   
    
    
    
    number_system='[b]Number systems[/b] are the technique to represent numbers in the computer system architecture, every value that you are saving or getting into/from computer memory has a defined number system.\n\nComputer architecture supports following number systems.\n     • Binary number system\n     • Octal number system\n     • Decimal number system\n     • Hexadecimal (hex) number system\n\nMachines interpret numbers differently from humans thus require a different system altogether. Whenever we type something on a device, those letters convert into certain numbers which only the computer can understand. A positional number system is what a device needs where there are digits and different values making up an entire number. Each digit has its own unique position and a symbol. Each digit’s value can be determined by the digit, position of the digit in the number, and the base of the number. '
    
    binary="[b]Binary Number System[/b] is used to define a number in binary system. Binary system is used to represent a number in terms of two numbers only, 0 and 1. The binary number system is used commonly by computer languages like Java, C++. As the computer only understands binary language that is 0 or 1, all inputs given to a computer are decoded by it into series of 0's or 1's to process it further. In this lesson we will learn how to convert a decimal number to its binary number and the conversion of binary number to decimal number. \n\nThe left most bit in the binary number is called as the Most Significant Bit (MSB) and it has the largest positional weight. The right most bit is the Least Significant Bit (LSB) and has the smallest positional weight."
    
    octal='[b]Octal Number System[/b] is a type of number system that has a base of eight and uses digits from 0 to 7. A number system is a system of naming, representing, or expressing numbers in different types of forms. The basic ways of representing numbers are done in four ways i.e. Octal Number System, Binary Number System, Decimal Number System, and Hexadecimal Number System.\n\nA number system with its base as eight and uses digits from 0 to 7 is called Octal Number System. The word octal is used to represent the numbers that have eight as the base. The octal numbers have many applications and importance such as it is used in computers and digital numbering systems. In the number system, octal numbers can be converted to binary numbers, binary numbers to octal numbers by first converting a binary number to decimal number then decimal number to octal number.'
    
    decimal='[b]Decimal Number System[/b] consists of 0,1,2,3,4,5,6,7,8,9 (10 digits). It is the oldest and most popular number system used in our day to day life. In the positional number system, each decimal digit is weighed relative to its position in the number. This means that each digit in the number is multiplied by 10 raised to a power corresponding to that digit’s position.\n\nIn computing, the binary , octal , or hexadecimal number system may be used instead of the decimal system. All these schemes have a number of digits that is a power of 2. This is an advantage in systems that use high and low digital states.\n\nNumber system having 10 digits from 0 to 9. This means that any numerical quantity can be represented using these 10 digits. Decimal number system is also a positional value system. This means that the value of digits will depend on its position.'
    
    hexadecimal="""A [b]Hexadecimal Number System[/b] is represented using base 16. Hexadecimal or Hex numbers are used as a shorthand form of binary sequence. This system is used to represent data in a more compact manner. Since 16 symbols are used, 0 to F, the notation is called hexadecimal. The first 10 symbols are the same as in the decimal system, 0 to 9 and the remaining 6 symbols are taken from the first 6 letters of the alphabet sequence, A to F, where A represents 10, B is 11, C is 12, D is 13, E is 14 and F is 15.\n\nHexadecimal number systems can be converted to other number systems such as binary number (base-2), octal number (base-8) and decimal number systems (base-10). Hexadecimal number system is used to describe locations in memory for every byte. These hexadecimal numbers are also easier to read and write than binary or decimal numbers for Computer Professionals."""
    
    ip_address="""[b]Internet Protocol[/b] addresses are used to identify hardware devices on a network. The addresses allow these devices to connect to one another and transfer data on a local network or over the internet.\n\nEach address is a string of numbers separated by periods. There are four numbers in total and each number can range between 0 and 255. An example of an IP address would be: 506.457.14.512\n\nWe need billions of IP addresses to identify every computer, router and website on the internet. One day we’ll run out of unique addresses and a new IPv6 protocol has been designed to meet this need.\n\nThe IP address space is managed globally by the Internet Assigned Numbers Authority (IANA), and by five regional Internet registries (RIRs) responsible in their designated territories for assignment to local Internet registries, such as Internet service providers (ISPs), and other end users."""
    
    mac_address="""[b]Media Access Control[/b] (MAC) address is the physical address, which uniquely identifies each device on a given network. To make communication between two networked devices, we need two addresses: IP address and MAC address. It is assigned to the NIC (Network Interface card) of each device that can be connected to the internet.\n\nIt stands for Media Access Control, and also known as Physical address, hardware address or BIA (Burned In Address).\n\nIt is globally unique; it means two devices cannot have the same MAC address. It is represented in a hexadecimal format on each device, such as 00:0a:95:9d:67:16.\n\nIt is 12-digit, and 48 bits long, out of which the first 24 bits are used for OUI(Organization Unique Identifier), and 24 bits are for NIC/vendor-specific."""
    
    
    
    
    
    
  


if __name__=='__main__':
    Content()